version: '3.8'

services:
  flask-app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - USE_DOCKER_SERVICE_NAMES=false
    network_mode: host
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
