version: '3.8'

services:
  flask1:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5001:1717"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - USE_DOCKER_SERVICE_NAMES=true
    networks:
      - flask_network
    volumes:
      - ./app:/app

  flask2:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5002:1717"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - USE_DOCKER_SERVICE_NAMES=true
    networks:
      - flask_network
    volumes:
      - ./app:/app

  flask3:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5003:1717"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - USE_DOCKER_SERVICE_NAMES=true
    networks:
      - flask_network
    volumes:
      - ./app:/app

networks:
  flask_network:
    driver: bridge
